version: '2'

services:
    gostation:
        image: langelog/gostation
        container_name: "gostation"
        restart: always
        volumes:
            - ./src:/app
        #ports:
        #    - "3000:3000"
        #    - "80:80"
        #    - "443:443"
        #    - "1337:1337"
        #    - "8080:8080"
        #links:
        #    - mysql
        command: bash
        stdin_open: true
        tty: true
